export const GALLERY_CONFIG = {
  totalImages: 10,
  tilesPerRevolution: 24,
  revolutions: 5.3,
  startRadius: 4.8,
  endRadius: 3,
  tileHeightRatio: 1.7,
  tileSegments: 32,
  spiralGap: 0.5,
  tileOverlap: 0.005,
  cameraPos: { x: 0, y: 4, z: 12 },
  cameraFov: 90,
  baseRotationSpeed: 0.0001,
  hasTextDecade: 7,
};
