import type { Metadata } from "next";

import { GalleryProvider } from "@/providers/GalleryProvider";

import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <GalleryProvider>{children}</GalleryProvider>
      </body>
    </html>
  );
}
